// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVBSEjyHOvXbvlOdzs_MOtNO_a1lHlZo',
    appId: '1:773878374124:web:825af71559ae997d80cfc9',
    messagingSenderId: '773878374124',
    projectId: 'readbuddycommunity',
    authDomain: 'readbuddycommunity.firebaseapp.com',
    storageBucket: 'readbuddycommunity.firebasestorage.app',
    measurementId: 'G-6H2HQ3WQ8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchLUV-x7yAAqtZh-ugekmrR06Mflj8Oc',
    appId: '1:773878374124:android:7cfa5c7f6526c5d580cfc9',
    messagingSenderId: '773878374124',
    projectId: 'readbuddycommunity',
    storageBucket: 'readbuddycommunity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRXvGHJzFUaVJZs_3dL526YV6Dtz7iA4',
    appId: '1:773878374124:ios:e67995b8797e430c80cfc9',
    messagingSenderId: '773878374124',
    projectId: 'readbuddycommunity',
    storageBucket: 'readbuddycommunity.firebasestorage.app',
    iosBundleId: 'com.readbuddy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbRXvGHJzFUaVJZs_3dL526YV6Dtz7iA4',
    appId: '1:773878374124:ios:0c9d401186f5236f80cfc9',
    messagingSenderId: '773878374124',
    projectId: 'readbuddycommunity',
    storageBucket: 'readbuddycommunity.firebasestorage.app',
    iosBundleId: 'com.example.readBuddyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmVBSEjyHOvXbvlOdzs_MOtNO_a1lHlZo',
    appId: '1:773878374124:web:ba6ffe3684c7600980cfc9',
    messagingSenderId: '773878374124',
    projectId: 'readbuddycommunity',
    authDomain: 'readbuddycommunity.firebaseapp.com',
    storageBucket: 'readbuddycommunity.firebasestorage.app',
    measurementId: 'G-QTVPY742XE',
  );
}
